# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Hw2_02.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(330, 434)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 291, 381))
        self.groupBox.setObjectName("groupBox")
        self.Find_Intrinsic_Matric = QtWidgets.QPushButton(self.groupBox)
        self.Find_Intrinsic_Matric.setGeometry(QtCore.QRect(10, 80, 271, 31))
        self.Find_Intrinsic_Matric.setObjectName("Find_Intrinsic_Matric")
        self.Find_Corners = QtWidgets.QPushButton(self.groupBox)
        self.Find_Corners.setGeometry(QtCore.QRect(10, 20, 271, 31))
        self.Find_Corners.setObjectName("Find_Corners")
        self.Find_Extrinsic_Matric = QtWidgets.QGroupBox(self.groupBox)
        self.Find_Extrinsic_Matric.setGeometry(QtCore.QRect(11, 137, 271, 121))
        self.Find_Extrinsic_Matric.setObjectName("Find_Extrinsic_Matric")
        self.label = QtWidgets.QLabel(self.Find_Extrinsic_Matric)
        self.label.setGeometry(QtCore.QRect(20, 30, 111, 21))
        self.label.setObjectName("label")
        self.pushButton_2 = QtWidgets.QPushButton(self.Find_Extrinsic_Matric)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 70, 241, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit = QtWidgets.QLineEdit(self.Find_Extrinsic_Matric)
        self.lineEdit.setGeometry(QtCore.QRect(130, 30, 131, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.Show_Results = QtWidgets.QPushButton(self.groupBox)
        self.Show_Results.setGeometry(QtCore.QRect(10, 340, 271, 31))
        self.Show_Results.setObjectName("Show_Results")
        self.Find_Distortion = QtWidgets.QPushButton(self.groupBox)
        self.Find_Distortion.setGeometry(QtCore.QRect(10, 280, 271, 31))
        self.Find_Distortion.setObjectName("Find_Distortion")
        self.Find_Intrinsic_Matric.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 330, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "2. Calibration"))
        self.Find_Intrinsic_Matric.setText(_translate("MainWindow", "2.2 Find Intrinsic"))
        self.Find_Corners.setText(_translate("MainWindow", "2.1 Find Corners"))
        self.Find_Extrinsic_Matric.setTitle(_translate("MainWindow", "2.3 Find Extrinsic"))
        self.label.setText(_translate("MainWindow", "Select image:"))
        self.pushButton_2.setText(_translate("MainWindow", "2.3 Find Extrinsic"))
        self.Show_Results.setText(_translate("MainWindow", "2.5 Show Results"))
        self.Find_Distortion.setText(_translate("MainWindow", "2.4 Find Distortion"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
